---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/kanidm_rlm_python"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: pip
    directory: "/pykanidm"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/kanidm_client"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/kanidm_proto"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/kanidmd/idm"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/kanidmd/score"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/kanidmd/daemon"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/kanidm_tools"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/kanidmd_web_ui"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/kanidm_unix_int"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
  - package-ecosystem: cargo
    directory: "/kanidm_unix_int/nss_kanidm"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/kanidm_unix_int/pam_kanidm"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/kanidm_unix_int/pam_tester"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/orca"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  - package-ecosystem: cargo
    directory: "/profiles"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Australia/Brisbane
    open-pull-requests-limit: 99