version = "2"
bindaddress = "[::]:8443"
ldapbindaddress = "127.0.0.1:3636"

db_fs_type = "zfs"
db_path = "/tmp/kanidm/kanidm.db"
tls_chain = "/tmp/kanidm/chain.pem"
tls_key = "/tmp/kanidm/key.pem"
# tls_client_ca = "/tmp/kanidm/client_ca"

#   The log level of the server. May be one of info, debug, trace
#
#   NOTE: this is overridden by KANIDM_LOG_LEVEL environment variable
#   Defaults to "info"
#
# log_level = "info"
log_level = "debug"
# log_level = "trace"

# otel_grpc_url = "http://localhost:4317"

domain = "localhost"
origin = "https://localhost:8443"

[online_backup]
# defaults to db_path
# path = "/tmp/kanidm/backups/"
schedule = "@hourly"
# enabled = true # default enabled

# default is gzip, but can also be "nocompression"
compression = "gzip"


[replication]
origin = "repl://127.0.0.1:8444"
bindaddress = "0.0.0.0:8444"


# [ldap_client_address_info]
# proxy-v2 = ["127.0.0.1", "127.0.0.0/8"]
# proxy-v1 = ["127.0.0.1", "127.0.0.0/8"]
