[package]
name = "kanidm_proto"
version = "1.1.0-alpha.6"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"
license = "MPL-2.0"
description = "Kanidm Protocol Bindings for serde"
documentation = "https://docs.rs/kanidm_proto/latest/kanidm_proto/"
homepage = "https://github.com/kanidm/kanidm/"
repository = "https://github.com/kanidm/kanidm/"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "0.8", features = ["serde", "wasm-bindgen"] }
# zxcvbn = { version = "2.0", features = ["ser"] }
base32 = "0.4"
webauthn-rs = { version = "0.3", default-features = false, features = ["wasm"] }
time = { version = "0.2", features = ["serde", "std"] }
url = { version = "2", features = ["serde"] }

[dev-dependencies]
serde_json = "1.0"

