[package]
name = "kanidm_proto"
version = "1.1.0-alpha.7"
authors = ["William Brown <william@blackhats.net.au>"]
rust-version = "1.59"
edition = "2021"
license = "MPL-2.0"
description = "Kanidm Protocol Bindings for serde"
documentation = "https://docs.rs/kanidm_proto/latest/kanidm_proto/"
homepage = "https://github.com/kanidm/kanidm/"
repository = "https://github.com/kanidm/kanidm/"

[dependencies]
serde = { version = "^1.0.136", features = ["derive"] }
serde_json = "^1.0.79"
uuid = { version = "^1.0.0", features = ["serde"] }
base32 = "^0.4.0"
webauthn-rs = { version = "^0.3.2", default-features = false, features = ["wasm"] }
# Can not upgrade due to breaking timezone apis.
time = { version = "=0.3.9", features = ["serde", "std"] }
url = { version = "^2.2.2", features = ["serde"] }

