[package]
name = "kanidm_proto"
version = "0.1.0"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"
license = "MPL-2.0"
description = "Kanidm Protocol Bindings for serde"
documentation = "https://docs.rs/kanidm_proto/latest/kanidm_proto/"
homepage = "https://github.com/Firstyear/kanidm/"
repository = "https://github.com/Firstyear/kanidm/"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
actix = { version = "0.7", optional = true }
zxcvbn = { version = "2.0", features = ["ser"] }

[dev-dependencies]
serde_json = "1.0"

