[package]
name = "daemon"
version = "0.1.0"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"
license = "MPL-2.0"
description = "Kanidm Server Daemon"
documentation = "https://docs.rs/kanidm/latest/kanidm/"
homepage = "https://github.com/kanidm/kanidm/"
repository = "https://github.com/kanidm/kanidm/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "kanidmd"
path = "src/main.rs"

[dependencies]
kanidm = { path = "../" }
score = { path = "../score" }
structopt = { version = "0.3", default-features = false }
users = "0.11"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.5"

[build-dependencies]
serde = { version = "1", features = ["derive"] }
structopt = { version = "0.3", default-features = false }
profiles = { path = "../../profiles" }
