[package]
name = "orca"
version = "1.1.0-alpha.7"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"
license = "MPL-2.0"
description = "Orca - load testing for LDAP and Kanidm"
documentation = "https://docs.rs/kanidm/latest/kanidm/"
homepage = "https://github.com/kanidm/kanidm/"
repository = "https://github.com/kanidm/kanidm/"

[[bin]]
name = "orca"
path = "src/main.rs"

[dependencies]
jemallocator = { version = "0.3.0", optional = true }
tracing = "0.1"
tracing-subscriber = "0.3"

structopt = { version = "0.3", default-features = false }

uuid = { version = "0.8", features = ["serde", "v4" ] }
csv = "1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

rand = "0.8"
toml = "0.5"

kanidm_proto = { path = "../kanidm_proto", version = "1.1.0-alpha" }
kanidm_client = { path = "../kanidm_client", version = "1.1.0-alpha" }

tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }
tokio-openssl = "0.6"
futures-util = "0.3"
openssl = "0.10"

ldap3_server = "^0.1.7"
# ldap3_server = { version = "0.1", path = "../../ldap3_server" }

crossbeam = "0.8"
async-std = { version = "1.6", features = ["tokio1"] }

mathru = "0.11"

