[package]
name = "profiles"
description = "Kanidm Build System Profiles"
documentation = "https://docs.rs/kanidm/latest/kanidm/"
# We do not have tests in this pkg
autotests = false

version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "profiles"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
toml.workspace = true
base64.workspace = true

[build-dependencies]
base64.workspace = true
