bindaddress = "127.0.0.1:8443"
ldapbindaddress = "127.0.0.1:3636"
db_path = "/tmp/kanidm.db"
db_fs_type = "zfs"
# tls_ca = "../insecure/ca.pem"
# tls_cert = "../insecure/cert.pem"
# tls_key = "../insecure/key.pem"
log_level = "verbose"
