bindaddress = "127.0.0.1:8443"
ldapbindaddress = "127.0.0.1:3636"

db_fs_type = "zfs"
db_path = "/tmp/kanidm/kanidm.db"
tls_chain = "/tmp/kanidm/chain.pem"
tls_key = "/tmp/kanidm/key.pem"

# log_level = "perfbasic"
# log_level = "quiet"
log_level = "verbose"

domain = "localhost"
origin = "https://localhost:8443"

