bindaddress = "127.0.0.1:8443"
ldapbindaddress = "127.0.0.1:3636"

db_fs_type = "zfs"
db_path = "/tmp/kanidm/kanidm.db"
tls_chain = "/tmp/kanidm/chain.pem"
tls_key = "/tmp/kanidm/key.pem"

#   The log level of the server. May be one of info, debug, trace
#
#   NOTE: this is overridden by environment variables at runtime
#   Defaults to "info"
#
# log_level = "info"
log_level = "debug"
# log_level = "trace"

# otel_grpc_url = "http://localhost:4317"

domain = "localhost"
origin = "https://localhost:8443"
trust_x_forward_for = true

[online_backup]
path = "/tmp/kanidm/backups/"
schedule = "@hourly"
