[package]
name = "kanidmd_core"
description = "Kanidm Server Core and Library"
documentation = "https://docs.rs/kanidm/latest/kanidm/"
autotests = false

version = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = { workspace = true }
axum = { workspace=true }
axum-auth = "0.4.0"
axum-csp = { workspace = true }
axum-macros = "0.3.8"
axum-server = { version = "0.5.1", features = ["tls-openssl"] }
bytes = { workspace = true }
chrono = { workspace = true }
compact_jwt = { workspace = true }
cron = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
http = "0.2.9"
hyper = { workspace = true }
kanidm_proto = { workspace = true }
kanidmd_lib = { workspace = true }
ldap3_proto = { workspace = true }
libc = { workspace = true }
openssl = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sketching = { workspace = true }
time = { workspace = true, features = ["serde", "std","local-offset"] }
tokio = { workspace = true, features = ["net", "sync", "io-util", "macros"] }
tokio-openssl = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
toml = {workspace = true}
tower = { version = "0.4.13", features = ["tokio-stream", "tracing"] }
tower-http = { version = "0.4.3", features = ["tokio", "tracing", "uuid", "compression-gzip", "compression-zstd", "trace", "fs"] }
tracing = { workspace = true, features = ["attributes"] }
tracing-subscriber = { workspace = true, features = ["time", "json"] }
urlencoding = { workspace = true }
kanidm_utils_users = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4" ] }
serde_with = "3.1.0"

[build-dependencies]
kanidm_build_profiles = { workspace = true }
