---
# mkdocs.yml
site_name: Kanidm Python library
use_directory_urls: false
theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  hljs_languages:
    - rust
    - json
    - yaml

repo_name: "kanidm/kanidm"
repo_url: "https://github.com/kanidm/kanidm"

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
  - gen-files:
      scripts:
        - docs/hooks/gen_files.py
watch:
  - "kanidm/"

nav:
  - "Home": index.md
  - "Client": kanidmclient.md
  - "Client Configuration": kanidmclientconfig.md
  - "RADIUS Client": radiusclient.md
  - "Token Storage": tokenstore.md
