[tool.poetry]
name = "kanidm"
version = "0.0.3"
description = "Kanidm client library"
license = "MPL-2.0"

authors = [
    "James Hodgkinson <james@terminaloutcomes.com>"
]

readme = "README.md"
repository = "https://github.com/kanidm/kanidm"
homepage = "https://kanidm.com/"

packages = [
    {include = "kanidm"},
    {include = "tests"},


]

keywords = [
    "kanidm",
    "idm",
    "api",
]
classifiers=[
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
[tool.poetry.dependencies]
python = "^3.8"
toml = "^0.10.2"
pydantic = "^1.9.2"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]
pylint = "^2.14.5"
mypy = "^0.971"
pytest = "^7.1.2"
types-toml = "^0.10.8"
pylint-pydantic = "^0.1.4"
coverage = "^6.4.3"
pylint-pytest = "^1.1.2"
pytest-asyncio = "^0.19.0"
pytest-mock = "^3.8.2"
pytest-aiohttp = "^1.0.4"
black = "^22.6.0"
mkdocs = "^1.3.1"
mkdocs-material = "^8.4.1"
mkdocstrings = "^0.19.0"
mkdocstrings-python = "^0.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.MASTER]
max-line-length=150
disable="W0511,raise-missing-from"
extension-pkg-whitelist="pydantic"
# https://github.com/samuelcolvin/pydantic/issues/1961#issuecomment-759522422
load-plugins="pylint_pydantic,pylint_pytest"


[tool.pytest.ini_options]
asyncio_mode = "auto"
markers = [
    "network: Tests that require network access",
]

[tool.coverage.run]
source = ["kanidm"]
omit = ["tests"]
