[tool.poetry]
name = "kanidm"
version = "0.0.3"
description = "Kanidm client library"
license = "MPL-2.0"

authors = [
    "James Hodgkinson <james@terminaloutcomes.com>"
]

readme = "README.md"
repository = "https://github.com/kanidm/kanidm"
homepage = "https://kanidm.com/"

packages = [
    {include = "kanidm"},
    {include = "tests"},
]

keywords = [
    "kanidm",
    "idm",
    "api",
]
classifiers=[
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
[tool.poetry.dependencies]
python = "^3.9"
toml = "^0.10.2"
pydantic = "^1.9.2"
aiohttp = "^3.8.1"
Authlib = "^1.1.0"

[tool.poetry.dev-dependencies]
mypy = "^1.2"
pytest = "^7.3.1"
types-toml = "^0.10.8"
pylint-pydantic = "^0.1.8"
coverage = "^7.2.3"
pylint-pytest = "^1.1.2"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.10.0"
pytest-aiohttp = "^1.0.4"
black = "^23.3.0"
mkdocs = "^1.4.2"
mkdocs-material = "^9.1.7"
mkdocstrings = "^0.21.2"
mkdocstrings-python = "^0.9.0"
pook = "^1.1.1"

[tool.poetry.group.dev.dependencies]
ruff = ">=0.0.230,<0.0.263"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.MASTER]
max-line-length=150
disable="W0511,raise-missing-from"
extension-pkg-allow-list="pydantic"
# https://github.com/samuelcolvin/pydantic/issues/1961#issuecomment-759522422
load-plugins="pylint_pydantic,pylint_pytest"

[tool.ruff]
line-length = 150

[tool.ruff.per-file-ignores]
"tests/*.py" = [
    "F401", # unused import, reused fixtures across all tests
    "F811", # pytest fixtures
]


[tool.pytest.ini_options]
asyncio_mode = "auto"
markers = [
    "network: Tests that require network access and a working backend server",
    "interactive: Requires specific config and a working backend server"
]

[tool.coverage.run]
source = ["kanidm"]
omit = ["tests"]

[tool.mypy]
plugins = "pydantic.mypy"
