[book]
authors = [
    "William Brown",
    "James Hodgkinson",
    "Carla Schroder",
]
language = "en"
multilingual = false
src = "src"
title = "Kanidm Administration"

[output.html]
edit-url-template = "https://github.com/kanidm/kanidm/edit/master/book/{path}"
git-repository-url = "https://github.com/kanidm/kanidm"

[preprocessor.template]
