---
name: Linting checks

# Trigger the workflow on push
"on":
  push:
  pull_request:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            libpam0g-dev \
            libselinux1-dev \
            libssl-dev \
            libsystemd-dev \
            libtss2-dev \
            libudev-dev \
            pkg-config \
            libtalloc-dev \
            tpm-udev && \
          sudo unix_integration/rlm_kanidm/pull_headers.sh
          echo "Looking at /usr/include/freeradius-devel/"
          ls -lah /usr/include/freeradius-devel/
          echo "######################"
          echo "Configure log"
          echo "######################"
          cat /tmp/freeradius_configure.log
          echo "######################"
          echo "Freeradius make log:"
          echo "######################"
          cat /tmp/freeradius_make.log
          echo "######################"

      - name: "Run clippy"
        run: |
          rustup component add clippy
          cargo clippy --quiet --lib --bins --examples --all-features
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: "Run cargo fmt"
        run: |
          rustup component add rustfmt
          cargo fmt --check
