---
# yamllint disable rule:line-length
name: Dependabot auto-approval and auto-merge
"on": pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # limit this to PRs opened by dependabot
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Show creator of the PR
        run: echo "PR created by ${{ github.event.pull_request.user.login }}"
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          alert-lookup: true
          compat-lookup: true
      - uses: actions/checkout@v5
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Approve a PR if not already approved
        run: scripts/dependabot_automerge_check.sh "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
