---
name: Container - Kanidmd

# this will build regardless,
# but only push to the container registry
# when you're committing on the master branch.

"on":
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  kanidmd_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # don't need qemu/buildx if we're not building ARM
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      -  # https://github.com/docker/login-action/#github-container-registry
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # don't log in if we're not going to push!
        if: ${{ github.ref == 'refs/heads/master' }} && ${{ github.repository == 'kanidm/kanidm' }}
      - name: Build and push kanidmd
        id: docker_build_kanidmd
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/master' }} && ${{ github.repository == 'kanidm/kanidm' }}
          platforms: linux/amd64
          tags: ghcr.io/kanidm/kanidmd:devel
          # build-args: |
          #   "KANIDM_BUILD_OPTIONS=-j1"
          file: server/Dockerfile
