---
name: Container - Radiusd

# this will build regardless,
# but only push to the container registry
# when you're committing on the master branch.

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  radius_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -  # https://github.com/docker/login-action/#github-container-registry
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # don't log in if we're not going to push!
        if: ${{ github.ref == 'refs/heads/master' }}
      - name: Build and push radius
        id: docker_build_radius
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: linux/arm64,linux/amd64
          # https://github.com/docker/build-push-action/issues/254
          tags: ghcr.io/kanidm/radius:devel
          context: .
          file: kanidm_rlm_python/Dockerfile
