---
name: Container - Kanidmd

# this will build regardless,
# but only push to the container registry
# when you're committing on the master branch.

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  kanidmd_build:
    runs-on: ubuntu-latest
    continue-on-error: true # yolo
    strategy:
      fail-fast: false
      matrix:
        target:
          # - linux/arm64
          - linux/amd64
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -  # https://github.com/docker/login-action/#github-container-registry
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push kanidmd
        id: docker_build_kanidmd
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: ${{matrix.target}}
          # https://github.com/docker/build-push-action/issues/254
          tags: ghcr.io/kanidm/kanidmd:devel
          build-args: |
            "KANIDM_BUILD_PROFILE=developer"
            "KANIDM_FEATURES="
            "KANIDM_BUILD_OPTIONS=-j1"
          file: kanidmd/Dockerfile
