---
name: PyKanidm tests

"on":
  push:
    branches:
      - "master"
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  python_tests:
    runs-on: ubuntu-latest
    env:
      UV_LINK_MODE: "copy"
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        run: pip install --root-user-action=ignore  uv
      - name: Running type checks
        run: |
          make test/pykanidm/typing
      - name: Running Linting
        run: |
          make test/pykanidm/lint
      - name: Running pytest
        run: |
          make test/pykanidm/pytest
