---
name: pykanidm - mypy

"on":
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pykanidm_mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Running mypy
        run: |
          cd pykanidm
          python --version
          python -m pip install --quiet --no-cache-dir --upgrade poetry
          poetry install
          poetry run mypy --strict kanidm tests
