---
name: PyKanidm tests

"on":
  push:
    branches:
      - "master"
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Running mypy
        run: |
          cd pykanidm
          python --version
          poetry install
          poetry run mypy --strict kanidm tests
      - name: Running Linting
        run: |
          cd pykanidm
          poetry install
          poetry run ruff --strict kanidm tests
      - name: Running pytest
        run: |
          cd pykanidm
          poetry install
          poetry run pytest -v
